### ISSUE TITLE
Setting usage description in main app will not display the usage text

### ISSUE THREAD

**Issue by cazador481** [rjbs/App-Cmd#43] opened 2015-01-16 19:05 UTC
I am trying to add usage text to the main app, and when I do it does not display the usage information when doing help
.
Example code.
```perl
package Foo;
use App::Cmd::Setup -app;
sub usage_desc { return 'hi';};
```

**Comment by rjbs** [comment] 2015-05-23 12:58
I can't believe I'm replying to this five months late. 😕  Sorry.

Anyway, I can't reproduce this problem.  If I run exactly the code you provided, tacking on `__PACKAGE__->new->run`, I do get `hi` in the output.

I'm closing this ticket only on the idea that after five months, you don't care, and I apologize for taking so long.  If you *do* still care and you *do* still see a problem with this, please re-open with details!

**Closed by rjbs** 2015-05-23 12:58 UTC
